FLAGS = -Wall -g
CC = gcc #if we want to change compiler

loops:
recursives:
recursived:
loopd:
mains:
maindloop:
maindrec:
all:
.PHONY: clean#.PHONY means that clean is not a file.
clean:
	rm -f *.o *.a *.so mains maindloop maindrec